### ISSUE TITLE
License request

### ISSUE THREAD

**Issue by fakefred** [krutarthpurohit/spi_protocol#1]
Hi Krutarth!

I'm a student at the University of Michigan, and my team would like to use this repo for our project. We would like to ask for explicit permission from you. One way you can grant this permission is to [add a license](https://choosealicense.com/licenses/). We accept any frequently used license, for example MIT or GPL.

If you prefer we do not use it, that is OK as well.

Thank you!

**Comment by krutarthpurohit** [comment]
Hi Frederick,

Thank you for reaching out! I’ve added the MIT License to the repository, so you’re free to use it for your project under those terms.

Feel free to make any modifications or additions you need. However, please create a new branch for any changes rather than modifying the main branch. This will keep the main branch stable while allowing your team to work independently.

Let me know if you have any questions, and best of luck with your project!

Best,
Krutarth
